const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN_USER: 'GET_TOKEN_USER',
    GET_TOKEN_TRAINER: 'GET_TOKEN_TRAINER',
    // GET_TOKEN_TRAINER: 'GET_TOKEN_TRAINER',
    GET_USER: 'GET_USER',
    GET_ALL_USER: 'GET_ALL_USER',
    LOGIN_TRAINER: 'LOGIN_TRAINER',
    LOGIN_USER: 'LOGIN_USER',
    GET_TRAINER: 'GET_TRAINER',
    GET_ALL_CATE: 'GET_ALL_CATE',
    GET_ALL_TUTORIAL: 'GET_ALL_TUTORIAL',
    GET_ALL_TUTORIAL_TRAINER: 'GET_ALL_TUTORIAL_TRAINER',
    GET_ALL_COURSES_TRAINER: 'GET_ALL_COURSES_TRAINER',
    GET_ALL_COURSES_USER: 'GET_ALL_COURSES_USER',
    GET_COURSES_TURORIAL: 'GET_COURSES_TURORIAL',
    GET_CHECK_REGISTER: 'GET_CHECK_REGISTER'
}
export default ACTIONS